# Generated by Django 4.1 on 2025-04-25 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografias_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografias',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
