# Generated by Django 4.1 on 2025-04-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografias_data_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografias',
            name='foto',
            field=models.ImageField(upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
